version: '3.8'
services:
  sales:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python sales.py'
    ports:
      - 8002:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    depends_on:
      - sales_db
    networks:
      - project_ok

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - sales_db
    networks:
      - project_ok

  sales_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sales
      MYSQL_USER: someone
      MYSQL_PASSWORD: someone
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    networks:
      - project_ok


networks:
  project_ok:
    name: project_ok
