version: '3.8'
services:
  sales:
    container_name: sales
    hostname: sales
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python sales.py'
    volumes:
      - .:/app
    depends_on:
      - sales_db
    networks:
      - project_tok
      - internet

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - sales_db
    networks:
      - project_tok
      - internet


  sales_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sales
      MYSQL_USER: someone
      MYSQL_PASSWORD: someone
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - project_tok
    expose:
      - 3306


networks:
  project_tok:
    name: project_tok
  internet:
    name: internet