version: '3.8'
services:
  warehouse:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python warehouse.py'
    # ports:
    #   - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db_warehouse
    networks:
      - project_tok

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db_warehouse
    networks:
      - project_tok
      - internet


  db_warehouse:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: warehouse
      MYSQL_USER: someone
      MYSQL_PASSWORD: someone
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - project_tok
    expose:
      - 3306

networks:
  project_tok:
    name: project_tok
  internet:
    name: internet