version: '3.8'
services:
  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_gateway
    hostname: api_gateway
    restart: always
    command: 'python gateway.py'
    volumes:
      - .:/app
    networks:
      - project_tok
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile_nginx
    container_name: nginx
    hostname: nginx
    restart: always
    networks:
      - project_tok
      - internet
    ports:
      - 80:80

networks:
  project_tok:
    name: project_tok
  internet:
    name: internet