version: '3.8'
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python auth.py'
    ports:
      - 8004:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - project_tok

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sales
      MYSQL_USER: someone
      MYSQL_PASSWORD: someone
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33080:3306
    networks:
      - project_tok

networks:
  project_tok:
    name: project_tok