version: '3.8'
services:
  accounting:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
    depends_on:
      - db_accounting
    networks:
      - project_ok

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db_accounting
    networks:
      - project_ok

  db_accounting:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: accounting
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - project_ok

networks:
  project_ok:
    name: project_ok