version: '3.8'
services:
  accounting:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    # ports:
    #   - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db_accounting
    networks:
      - project_tok
    expose:
      - 8000

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db_accounting
    networks:
      - project_tok
      - internet

  db_accounting:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: accounting
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - project_tok
    expose:
      - 3306

networks:
  project_tok:
    name: project_tok
  internet:
    name: internet