# Generated by Django 3.1.7 on 2023-05-30 11:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CRYPTO', 'Crypto'), ('VISA', 'VISA'), ('PAYPAL', 'Paypal')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('order_id', models.UUIDField()),
                ('amount', models.FloatField()),
                ('description', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.payment')),
            ],
        ),
    ]
